### ISSUE TITLE
Missing support for eu-west-3?

### ISSUE THREAD

**Issue by niezbop** [ex-aws/ex_aws#541]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 20 [erts-9.2] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10]

Elixir 1.6.1 (compiled with OTP 19)
```
* ExAws version `mix deps | grep ex_aws`
```
* ex_aws 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ex_aws) 8df2f96f
* ex_aws_s3 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_s3) 404e7951
```
* HTTP client version. IE for hackney do `mix deps | grep hackney`
```
* hackney 1.11.0 (Hex package) (rebar3)
  locked at 1.11.0 (hackney) 4951ee01
```

### Current behavior

I am trying to get my elixir application to communicate with my S3 bucket which is located in Paris (so `eu-west-3`), but I am facing this issue: `s3 not supported in region eu-west-3 for partition aws`.

__config.exs__

```elixir
config :ex_aws, :s3,
  scheme: "https://",
  host: "s3-eu-west-3.amazonaws.com",
  region: "eu-west-3",
  access_key_id: [{:system, "AWS_S3_KEY"}, :instance_role],
  secret_access_key: [{:system, "AWS_S3_SECRET"}, :instance_role]
```

__Code samples that throw the issue__

```elixir
ExAws.S3.list_objects("some.bucket")
|> ExAws.request!
```
```elixir
ExAws.S3.presigned_url(ExAws.Config.new(:s3), :get, "some.bucket", "some.item")
```

__Trace__

```
** (exit) an exception was raised:
    ** (RuntimeError) s3 not supported in region eu-west-3 for partition aws
        (ex_aws) lib/ex_aws/config/defaults.ex:107: ExAws.Config.Defaults.fetch_or/3
        (ex_aws) lib/ex_aws/config/defaults.ex:94: ExAws.Config.Defaults.do_host/3
        (ex_aws) lib/ex_aws/config/defaults.ex:37: ExAws.Config.Defaults.get/2
        (ex_aws) lib/ex_aws/config.ex:38: ExAws.Config.build_base/2
        (ex_aws) lib/ex_aws/config.ex:29: ExAws.Config.new/2
        (ex_aws) lib/ex_aws.ex:49: ExAws.request/2
        (ex_aws) lib/ex_aws.ex:61: ExAws.request!/2
        (my_app) lib/my_app_web/controllers/image_controller.ex:8: ChesskingdomBackendWeb.ImageController.show/2
        (my_app) lib/my_app_web/controllers/image_controller.ex:1: ChesskingdomBackendWeb.ImageController.action/2
        (my_app) lib/my_app_web/controllers/image_controller.ex:1: ChesskingdomBackendWeb.ImageController.phoenix_controller_pipeline/2
        (my_app) lib/my_app_web/endpoint.ex:1: ChesskingdomBackendWeb.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (my_app) lib/my_app_web/endpoint.ex:1: ChesskingdomBackendWeb.Endpoint.plug_builder_call/2
        (my_app) lib/plug/debugger.ex:99: ChesskingdomBackendWeb.Endpoint."call (overridable 3)"/2
        (my_app) lib/my_app_web/endpoint.ex:1: ChesskingdomBackendWeb.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) some/path/my_app/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

### Expected behavior

I would expect to be able to interact with my french bucket as I would with my american one or with my german one 😄
I have taken a look at the trace and I believe that this is an issue of the [priv/endpoint.exs](https://github.com/ex-aws/ex_aws/blob/master/priv/endpoints.exs) file which lacks the correct information regarding `eu-west-3`, so I'm wondering whether this is intentional or accidental?

Cheers, and thanks for this service 👍 
Paul

**Comment by lacostej** [comment]
Maybe this #531 ?

**Comment by niezbop** [comment]
This PR should probably do the trick if I understand the issue correctly

**Comment by benwilson512** [comment]
Handled in master.
