### ISSUE TITLE
Missing Poison.decode

### ISSUE THREAD

**Issue by meox** [ex-aws/ex_aws#613]
### Environment

* Elixir 1.7.4
* ExAws version: 2.0.2
* HTTP client version: 1.14.3

### Current behavior

```text
##### [2019-01-03 16:46:16.416] [error]  GenServer :worker_supervisor terminating
** (UndefinedFunctionError) function Poison.decode/1 is undefined (module Poison is not available)
    Poison.decode("<?xml version=\"1.0\"?><ErrorResponse xmlns=\"http://queue.amazonaws.com/doc/2012-11-05/\"><Error><Type>Sender</Type><Code>AWS.SimpleQueueService.NonExistentQueue</Code><Message>The specified queue does not exist for this wsdl version.</Message><Detail/></Error><RequestId>8c4a52a5-26b8-50db-b812-060d1820de60</RequestId></ErrorResponse>")
    (ex_aws) lib/ex_aws/request.ex:58: ExAws.Request.client_error/2
    (ex_aws) lib/ex_aws/request.ex:42: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/query.ex:33: ExAws.Operation.ExAws.Operation.Query.perform/2
    (pulsar_solr_indexer) lib/sqs_consumer.ex:38: SQSConsumer.handle_info/2
    (gen_stage) lib/gen_stage.ex:2036: GenStage.noreply_callback/3
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
```

### Expected behavior

don't crash

**Comment by tielur** [comment]
@meox did you get an answer to this, I'm experiencing this issue now as well

**Comment by meox** [comment]
try this:
```
config :ex_aws,
  ...
  json_codec: Jason
```
