### ISSUE TITLE
sweet xml error when retrieving cloudwatch metric statistics

### ISSUE THREAD

**Issue by brpandey** [ex-aws/ex_aws#645]
Not sure where this goes - ex_aws or ex_aws_cloudwatch

The aws CLI tools works fine when I run get-metric_statistics -- I always get data

```
aws --profile XXXdev_admin cloudwatch get-metric-statistics --metric-name CPUUtilization --start-time 2019-07-15T21:54:55.096486Z --end-time 2019-07-16T21:54:55.096486Z --period 3600 --namespace AWS/EC2 --statistics Average --dimensions Name=InstanceId,Value=i-XXX61

{
    "Label": "CPUUtilization",
    "Datapoints": [
        {
            "Timestamp": "2019-07-16T01:54:00Z",
            "Average": 0.11666666666666667,
            "Unit": "Percent"
        }, 
... 
}
```
However when I run using ExAws/ExAws.Cloudwatch, I get the SweetXML(v0.6.6) error below
```
iex(15)> x
%ExAws.Operation.Query{
  action: :get_metric_statistics,
  params: %{
    "Action" => "GetMetricStatistics",
    "Dimensions.member.1.Name" => "InstanceId",
    "Dimensions.member.1.Value" => "i-XXX61",
    "EndTime" => "2019-07-16T21:54:55.096486Z",
    "MetricName" => "CPUUtilization",
    "Namespace" => "AWS/EC2",
    "Period" => 3600,
    "StartTime" => "2019-07-15T21:54:55.096486Z",
    "Statistics.member.1" => "Average",
    "Version" => "2010-08-01"
  },
  parser: &ExAws.Cloudwatch.Parsers.parse/2,
  path: "/",
  service: :monitoring
}
iex(16)> x |> ExAws.request()
** (MatchError) no match of right hand side value: :error
    (sweet_xml) lib/sweet_xml.ex:667: SweetXml.to_cast/3
    (sweet_xml) lib/sweet_xml.ex:441: SweetXml.xpath/2
    (sweet_xml) lib/sweet_xml.ex:531: anonymous fn/3 in SweetXml.xmap/3
    (elixir) lib/map.ex:791: Map.get_and_update/3
    (sweet_xml) lib/sweet_xml.ex:531: SweetXml.xmap/3
    (sweet_xml) lib/sweet_xml.ex:530: SweetXml.xmap/3
    (elixir) lib/enum.ex:1327: Enum."-map/2-lists^map/1-0-"/2
    (sweet_xml) lib/sweet_xml.ex:526: anonymous fn/4 in SweetXml.xmap/3
```

Its not clear what is actually happening and what the aws response was?

I will say that 

```
    ExAws.Cloudwatch.list_metrics(namespace: "AWS/EC2") |> ExAws.request()
```

works everytime

**Comment by benwilson512** [comment]
This should be on the cloud watch repository, that's where the parser is defined.
