### ISSUE TITLE
presigned_url throw argument error of expected keyword list instead of two element tuple

### ISSUE THREAD

**Issue by xshadowlegendx** [ex-aws/ex_aws#724]
## Environment

* Elixir & Erlang versions (elixir --version): 1.11.1
* ExAws version `mix deps |grep ex_aws` 2.1.1
* HTTP client version. IE for hackney do `mix deps | grep hackney` 1.15.2

### Current behavior

got error thrown when try to get presign url

Include code samples, errors and stacktraces if appropriate.

stack trace

```
[error] ** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {"host", "my-bucket.s3.amazonaws.com"}
    (elixir 1.11.1) lib/keyword.ex:475: Keyword.keys/1
    (ex_aws 2.1.1) lib/ex_aws/auth.ex:271: ExAws.Auth.build_amz_query_params/5
    (ex_aws 2.1.1) lib/ex_aws/auth.ex:77: ExAws.Auth.presigned_url/9
    (app_server 3.6.10) lib/app_server/file_upload.ex:22: AppServer.FileUpload.presigned_url/2
    (app_server 3.6.10) lib/app_server_web/resolvers/file.ex:16: AppServerWeb.Resolvers.File.gen_presigned_url/3
    (absinthe 1.4.16) lib/absinthe/resolution.ex:209: Absinthe.Resolution.call/2
    (app_server 3.6.10) lib/app_server_web/middlewares/catch_all.ex:31: AppServerWeb.Middlewares.CatchAll.exec_safely/2
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:209: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:168: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/4
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:153: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:72: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:53: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
    (absinthe 1.4.16) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
    (absinthe 1.4.16) lib/absinthe/pipeline.ex:274: Absinthe.Pipeline.run_phase/3
    (absinthe_plug 1.4.7) lib/absinthe/plug.ex:421: Absinthe.Plug.run_query/4
    (absinthe_plug 1.4.7) lib/absinthe/plug.ex:247: Absinthe.Plug.call/2
    (phoenix 1.4.10) lib/phoenix/router/route.ex:40: Phoenix.Router.Route.call/2
    (phoenix 1.4.10) lib/phoenix/router.ex:288: Phoenix.Router.__call__/2
    (app_server 3.6.10) lib/app_server_web/endpoint.ex:1: AppServerWeb.Endpoint.plug_builder_call/2
    (app_server 3.6.10) lib/plug/debugger.ex:122: AppServerWeb.Endpoint."call (overridable 3)"/2
```

`presigned_url` function within `AppServer.FileUpload` module

```
def presigned_url(file_type, path) do
    uuid = UUID.uuid5(UUID.uuid4(), random_string())

    file_ext = grep_file_ext(file_type)

    query_params = [
      {"Content-Type", file_type},
      {"ACL", "private"},
      {"Content-Length", max_content_length(file_ext)}
    ]
    presign_options = [virtual_host: false, query_params: query_params]

    filename = "#{uuid}.#{file_ext}"

    {:ok, upload_url} =
      :s3
      |> ExAws.Config.new()
      |> ExAws.S3.presigned_url(:put, path, filename, presign_options)

    %{upload_url: upload_url, url: "#{path}/#{filename}"}
end
```

`config.exs`

```
config :ex_aws,
  debug_requests: Mix.env() != :prod,
  access_key_id: System.get_env("AWS_API_KEY"),
  secret_access_key: System.get_env("AWS_API_SECRET"),
  s3: [
    scheme: "https://",
    host: "#{System.get_env("AWS_BUCKET_NAME")}" <> ".s3.amazonaws.com",
    region: System.get_env("AWS_BUCKET_REGION")
  ]
```

The presigned url does not work both in local development and dockerized, it works before until recently I discover that file upload does not work when developing new feature which is unrelated to file upload but I try to manual test the whole process before deploying update.

I also tried listing objects in the bucket to check if basic thing works but it also does not

```
iex(3)> "my-bucket" |> ExAws.S3.list_objects() |> ExAws.request()
** (ArgumentError) expected a keyword list, but an entry in the list is not a two-element tuple with an atom as its first element, got: {"content-length", 0}
    (elixir 1.11.1) lib/keyword.ex:475: Keyword.keys/1
    (ex_aws 2.1.1) lib/ex_aws/auth.ex:163: ExAws.Auth.build_canonical_request/5
    (ex_aws 2.1.1) lib/ex_aws/auth.ex:146: ExAws.Auth.signature/8
    (ex_aws 2.1.1) lib/ex_aws/auth.ex:130: ExAws.Auth.auth_header/7
    (ex_aws 2.1.1) lib/ex_aws/auth.ex:45: ExAws.Auth.headers/6
    (ex_aws 2.1.1) lib/ex_aws/request.ex:29: ExAws.Request.request_and_retry/7
    (ex_aws 2.1.1) lib/ex_aws/operation/s3.ex:39: ExAws.Operation.ExAws.Operation.S3.perform/2
```

### Expected behavior

the function successfully return `upload_url` and `url` to the file

**Comment by xshadowlegendx** [comment]
the problem gone after update `ex_aws` library to `2.1.6`

**Comment by axelson** [comment]
I believe this was fixed in this commit: https://github.com/ex-aws/ex_aws/commit/d598effef7f7c9e110c4e991fb68d6c5a922aaff
