### ISSUE TITLE
>= 2.3.0 AuthCache issue

### ISSUE THREAD

**Issue by cpursley** [ex-aws/ex_aws#891]
### Environment

* Elixir 1.13.4 & Erlang 24.3.3
* ex_aws 2.2.10 & ex_aws_s3  2.3.3
* hackney 1.18.1

### Current behavior

After upgrading from `2.2.10` -> `2.3.0` on Elixir `1.13.4`, I'm getting this error:

```
(ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 3.17.1) :ets.lookup(ExAws.Config.AuthCache, :aws_instance_auth)

Stacktrace:
  │ (ex_aws 2.3.2) lib/ex_aws/config/auth_cache.ex:23: ExAws.Config.AuthCache.get/1
  │ (ex_aws 2.3.2) lib/ex_aws/config.ex:112: ExAws.Config.retrieve_runtime_value/2
  │ (elixir 1.13.4) lib/stream.ex:572: anonymous fn/4 in Stream.map/2
  │ (elixir 1.13.4) lib/enum.ex:4475: Enumerable.List.reduce/3
  │ (elixir 1.13.4) lib/stream.ex:1719: Enumerable.Stream.do_each/4
  │ (elixir 1.13.4) lib/enum.ex:1112: Enum.find/3
  │ (ex_aws 2.3.2) lib/ex_aws/config.ex:99: anonymous fn/2 in ExAws.Config.retrieve_runtime_config/1
```

**Comment by bernardd** [comment]
Most likely ex_aws app isn't being properly started in your app. In earlier versions this didn't matter because there was no setup to do, but as of 2.3 it must be started along with other dependant apps.
