### ISSUE TITLE
Add timestream to aws-us-gov partition

### ISSUE THREAD

**Issue by lugomateo** [ex-aws/ex_aws#939]
### Environment

- Erlang/OTP 25 [erts-13.1.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [jit:ns]
- Elixir (1.13.4)
- {:ex_aws, "~> 2.3.2"},
- {:ex_aws_timestream, "~> 0.5.1"},
- {:hackney, "~> 1.9"},
- {:jason, "~> 1.2"},

### Current behavior
```
> ExAws.Timestream.list_databases |> ExAws.request(region: "us-gov-west-1")
** (RuntimeError) ingest_timestream not found in partition aws-us-gov
    (ex_aws 2.3.4) lib/ex_aws/config/defaults.ex:175: ExAws.Config.Defaults.fetch_or/3
    (ex_aws 2.3.4) lib/ex_aws/config/defaults.ex:147: ExAws.Config.Defaults.do_host/3
    (ex_aws 2.3.4) lib/ex_aws/config/defaults.ex:89: ExAws.Config.Defaults.get/2
    (ex_aws 2.3.4) lib/ex_aws/config.ex:70: ExAws.Config.build_base/2
    (ex_aws 2.3.4) lib/ex_aws/config.ex:43: ExAws.Config.new/2
    (ex_aws 2.3.4) lib/ex_aws.ex:73: ExAws.request/2
```

### Expected behavior

Should list tables in `us-gov-west-1`

**Comment by bernardd** [comment]
Thanks @lugomateo - happy to take a PR with this change in it if you'd like to submit one.
